"""Verificando relacionamentos nas classes

Revision ID: 8074fadb3d03
Revises: c982d93f50c4
Create Date: 2024-05-09 21:03:50.053875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8074fadb3d03'
down_revision: Union[str, None] = 'c982d93f50c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
